version: '2.3'

services:

  face_recon:
    image: face_recon
    container_name: face_recon
    working_dir: /face_recon
    build: .
    volumes:
      - ../src:/face_recon
      - ../data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=unix$DISPLAY
    runtime: nvidia

